// <auto-generated />
using System;
using APIAcademia.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIAcademia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIAcademia.Model.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaminhoFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAti")
                        .HasColumnType("bit");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("APIAcademia.Model.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("CamonhoFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAti")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Equipamentos");
                });

            modelBuilder.Entity("APIAcademia.Model.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaminhoVideo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipamentoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAti")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParteDoCorpoTreino")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.ToTable("Exercicios");
                });

            modelBuilder.Entity("APIAcademia.Model.ExercicioTreino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExercicioId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAti")
                        .HasColumnType("bit");

                    b.Property<int?>("Repeticoes")
                        .HasColumnType("int");

                    b.Property<int?>("Series")
                        .HasColumnType("int");

                    b.Property<int?>("TreinoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExercicioId")
                        .IsUnique()
                        .HasFilter("[ExercicioId] IS NOT NULL");

                    b.HasIndex("TreinoId");

                    b.ToTable("ExericiosTreino");
                });

            modelBuilder.Entity("APIAcademia.Model.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaminhoFoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cargo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAti")
                        .HasColumnType("bit");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeMae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalarioHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("APIAcademia.Model.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAti")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("APIAcademia.Model.Manutencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("EquipamentoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAti")
                        .HasColumnType("bit");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EquipamentoId");

                    b.ToTable("Manutencaoes");
                });

            modelBuilder.Entity("APIAcademia.Model.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Especialidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAti")
                        .HasColumnType("bit");

                    b.Property<int>("funcionarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("funcionarioId")
                        .IsUnique();

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("APIAcademia.Model.Treino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAti")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("Treinos");
                });

            modelBuilder.Entity("APIAcademia.Model.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoIlustracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAti")
                        .HasColumnType("bit");

                    b.Property<string>("NomeFatasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("APIAcademia.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoAcessoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAti")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId")
                        .IsUnique();

                    b.HasIndex("GrupoAcessoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("UnidadeUsuario", b =>
                {
                    b.Property<int>("UsuarioTemUnidadeId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioTemUnidadeId1")
                        .HasColumnType("int");

                    b.HasKey("UsuarioTemUnidadeId", "UsuarioTemUnidadeId1");

                    b.HasIndex("UsuarioTemUnidadeId1");

                    b.ToTable("UnidadeUsuario");
                });

            modelBuilder.Entity("APIAcademia.Model.Aluno", b =>
                {
                    b.HasOne("APIAcademia.Model.Unidade", "Unidade")
                        .WithMany("Alunos")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("APIAcademia.Model.Equipamento", b =>
                {
                    b.HasOne("APIAcademia.Model.Unidade", "Unidade")
                        .WithMany("Equipamentos")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("APIAcademia.Model.Exercicio", b =>
                {
                    b.HasOne("APIAcademia.Model.Equipamento", "Equipamento")
                        .WithMany("Exercicios")
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipamento");
                });

            modelBuilder.Entity("APIAcademia.Model.ExercicioTreino", b =>
                {
                    b.HasOne("APIAcademia.Model.Exercicio", "Exercicio")
                        .WithOne("EquipamentoTreino")
                        .HasForeignKey("APIAcademia.Model.ExercicioTreino", "ExercicioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("APIAcademia.Model.Treino", "Treino")
                        .WithMany()
                        .HasForeignKey("TreinoId");

                    b.Navigation("Exercicio");

                    b.Navigation("Treino");
                });

            modelBuilder.Entity("APIAcademia.Model.Funcionario", b =>
                {
                    b.HasOne("APIAcademia.Model.Unidade", "Unidade")
                        .WithMany("Funcionarios")
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("APIAcademia.Model.Manutencao", b =>
                {
                    b.HasOne("APIAcademia.Model.Equipamento", "Equipamento")
                        .WithMany("Manutencoes")
                        .HasForeignKey("EquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipamento");
                });

            modelBuilder.Entity("APIAcademia.Model.Professor", b =>
                {
                    b.HasOne("APIAcademia.Model.Funcionario", "Funcionario")
                        .WithOne("Professor")
                        .HasForeignKey("APIAcademia.Model.Professor", "funcionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("APIAcademia.Model.Treino", b =>
                {
                    b.HasOne("APIAcademia.Model.Aluno", "Aluno")
                        .WithMany("Treinos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("APIAcademia.Model.Usuario", b =>
                {
                    b.HasOne("APIAcademia.Model.Funcionario", "Funcionario")
                        .WithOne("Usuario")
                        .HasForeignKey("APIAcademia.Model.Usuario", "FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("APIAcademia.Model.Grupo", "Grupo")
                        .WithMany("Usuarios")
                        .HasForeignKey("GrupoAcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("UnidadeUsuario", b =>
                {
                    b.HasOne("APIAcademia.Model.Unidade", null)
                        .WithMany()
                        .HasForeignKey("UsuarioTemUnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIAcademia.Model.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioTemUnidadeId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APIAcademia.Model.Aluno", b =>
                {
                    b.Navigation("Treinos");
                });

            modelBuilder.Entity("APIAcademia.Model.Equipamento", b =>
                {
                    b.Navigation("Exercicios");

                    b.Navigation("Manutencoes");
                });

            modelBuilder.Entity("APIAcademia.Model.Exercicio", b =>
                {
                    b.Navigation("EquipamentoTreino");
                });

            modelBuilder.Entity("APIAcademia.Model.Funcionario", b =>
                {
                    b.Navigation("Professor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("APIAcademia.Model.Grupo", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("APIAcademia.Model.Unidade", b =>
                {
                    b.Navigation("Alunos");

                    b.Navigation("Equipamentos");

                    b.Navigation("Funcionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
